disease_index = ("Apple with Apple_scab ",
	"Apple with Black Rot",
	"Apple with Cedar apple rust",
	"healthy Apples","random background image",
	"healthy Blueberry",
	"healthy Cherry",
	"Cherry with Powdery Mildew",
	"Corn with Cercospora leaf spot",
	"Corn with Common rust",
	"healthy Corn",
	"Northern Leaf Blight in Corn",
	"Black Rot in Grape",
	"Black Measels in Grape",
	"healthy Grape",
	"Isariopsis Leaf Spot in Grape",
	"Citrus greening in Orange",
	"Bacterial Spot in Peach",
	"healthy Peach",
	"Pepper with Bacterial Spot",
	"Healthy Pepper",
	"Potato Early Blight",
	"Healthy Potato",
	"Potato with Late Blight",
	"Healthy Raspberry",
	"healthy Soyabean",
	"Powdery Mildew in Squash",
	"Healthy Strawberry",
	"Strawberry with Leaf Scorch",
	"Tomato with Bacterial Spot",
	"Tomato with Early Blight",
	"Healthy Tomato",
	"Late blight in Tomato",
	"Tomato with Leaf Mold",
	"Tomato with Septoria Leaf Spot",
	"tomato with Spider Mites",
	"Tomato with Target Spots",
	"Tomato with Mosaic Virus",
	"Yellow Leaf Curl in Tomato")


alldis=[{"1":"1"},
{"2":"2"},
{"3":"3"},
{"4":"4"}]
