# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='disease',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
