# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_plantimage_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
