# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_plantimage_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('publish', models.DateField()),
            ],
        ),
    ]
